<?php
function live_tweets_block($op='list', $delta=0, $edit=array()) {

   switch ($op) {
     case 'list':
       $blocks[0]['info'] = t('Live tweets');
       return $blocks;
     case 'view':
       $blocks['subject'] = t('Live Tweets');
       $blocks['content'] = t('Loading tweets...');       
       return $blocks;
     case 'configure':
      $form['live_tweets'] = array(
      '#type' => 'fieldset',
      '#title' => t('Live tweets'),
      '#tree' => TRUE,
      );
      $form['live_tweets']['keywords'] = array(
      '#type' => 'textfield',
      '#title' => t('Search query'),
      '#default_value' => variable_get('live_tweets_block_keywords', 'Drupal'),
      '#description' => t('List of keywords and operators separated by spaces. ex: keyword OR from:user See !url for more info.', array ('!url' => l('http://search.twitter.com/api/', null)) ),
      );
      $form['live_tweets']['ntweets'] = array(
      '#type' => 'select',
      '#title' => t('Number of tweets'),
      '#description' => t('Number of tweets that will be displayed'),
      '#default_value' => variable_get('live_tweets_block_ntweets', 3),
      '#options' => array('3' => 3, '4' => 4, '5' => 5,  '6' => 6, '10' => 12),
      );
      $form['live_tweets']['refresh'] = array(
      '#type' => 'select',
      '#title' => t('Refresh time'),
      '#description' => t('Time interval to search for new tweets'), 
      '#default_value' => variable_get('live_tweets_block_refresh', 30),
      '#options' => array('10' => '10s', '20' => '20s', '30' => '30s', '60' => '1min'),
      );
      return $form;
      
     case 'save':
       variable_set('live_tweets_block_keywords', check_plain($edit['live_tweets']['keywords']));
       variable_set('live_tweets_block_ntweets', check_plain($edit['live_tweets']['ntweets']));
       variable_set('live_tweets_block_refresh', check_plain($edit['live_tweets']['refresh']));
      return null; 
   }

}
/*
 *  Implementation of hook_init()
 */
function live_tweets_init() {
       $path = drupal_get_path('module', 'live_tweets');       
       drupal_add_js($path . '/js/live_tweets.js');
       drupal_add_js(array('live_tweets' => array(
              'keywords' => urlencode(variable_get('live_tweets_block_keywords', 'Drupal')),
              'ntweets' => variable_get('live_tweets_block_ntweets', '3'),
              'refresh' => variable_get('live_tweets_block_refresh', 30) * 1000,
       )), 'setting');
}